// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs qr-generator`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "strip-tracking",
    "icon": "🧹",
    "name": {
      "en": "Strip Tracking Params",
      "ja": "URLトラッキング除去",
      "zh": "移除追踪参数",
      "de": "Tracking-Parameter entfernen",
      "es": "Eliminar parámetros de rastreo"
    },
    "desc": {
      "en": "Remove UTM/fbclid/gclid and other tracking params from a URL.",
      "ja": "URLからUTM/fbclid/gclidなどのトラッキングパラメータを除去。",
      "zh": "从网址中移除 UTM/fbclid/gclid 等追踪参数。",
      "de": "Entferne UTM/fbclid/gclid und andere Tracking-Parameter aus einer URL.",
      "es": "Elimina UTM/fbclid/gclid y otros parámetros de rastreo de una URL."
    }
  },
  {
    "slug": "encode-base64",
    "icon": "🔤",
    "name": {
      "en": "Encode Base64",
      "ja": "Base64エンコード",
      "zh": "Base64 编解码",
      "de": "Base64 kodieren",
      "es": "Codificar Base64"
    },
    "desc": {
      "en": "Encode or decode Base64, for text or binary files, byte-for-byte.",
      "ja": "テキスト・バイナリファイルをBase64に相互変換。バイト完全一致。",
      "zh": "对文本或二进制文件进行 Base64 编码或解码，逐字节还原。",
      "de": "Base64 für Text- oder Binärdateien kodieren oder dekodieren, Byte für Byte.",
      "es": "Codifica o decodifica Base64 para texto o archivos binarios, byte a byte."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'qr-generator';
